name: Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: zellestamas/gitcraft_simpletest:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the application
        run: make build
      - name: Run test script
        run: make test
      - name: Check result of test
        run: make io-diff-tests

  cppcheck:
    runs-on: ubuntu-latest
    container: zellestamas/gitcraft_simpletest:latest
    steps:
      - uses: actions/checkout@v2
      - name: Run code analysis
        run: make static-code-analysis
      - uses: actions/upload-artifact@v2
        with:
          path: ./warning_style.txt
      - uses: actions/upload-artifact@v2
        with:
          path: ./warning_perform.txt
          
  valgrind:
    runs-on: ubuntu-latest
    container: zellestamas/gitcraft_simpletest:latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make build
      - name: Run code memcheck
        run: make memory-leak-check