name: Unit Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libgtest-dev && sudo apt install cmake
      - name: Unit tests
        run: make parser-tests