name: Unit Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: zellestamas/gitcraft_unit:latest 
    steps:
      - uses: actions/checkout@v2
      - name: Create references
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Unit tests
        run: make parser-tests