name: Unit Test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: zellestamas/gitcraft_unit:latest 
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: make parser-tests